# Generated by Django 5.2.6 on 2025-10-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_talks_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='From',
            field=models.CharField(max_length=150),
        ),
    ]
