# Generated by Django 5.2.6 on 2025-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_notifications_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
            ],
        ),
    ]
