# Generated by Django 5.2.6 on 2025-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employess',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
