# Generated by Django 5.2.6 on 2025-10-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_employess_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employess'),
        ),
    ]
