# Generated by Django 5.2.6 on 2025-10-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_talks_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talks',
            name='emp',
        ),
    ]
